export const recursos = [
  {
    label: "A",
    name: "Pointer",
    quantity: 0,
    currentCost: 15,
    initialCost: 15,
    currentIncome: 0,
    income: 0.1,
  },
  {
    label: "B",
    name: "Grandma",
    quantity: 0,
    currentCost: 100,
    initialCost: 100,
    currentIncome: 0,
    income: 0.5,
  },
  {
    label: "C",
    name: "Farm",
    quantity: 0,
    currentCost: 500,
    initialCost: 500,
    currentIncome: 0,
    income: 4,
  },
  {
    label: "D",
    name: "Mine",
    quantity: 0,
    currentCost: 3000,
    initialCost: 3000,
    currentIncome: 0,
    income: 10,
  },
  {
    label: "E",
    name: "Factory",
    quantity: 0,
    currentCost: 40000,
    initialCost: 40000,
    currentIncome: 0,
    income: 40,
  },
]